In [1]:
import numpy as np


In [3]:
n_array = np.array([1,2,3])

In [5]:
print(n_array)



[1 2 3]


In [6]:
nl_array = np.zeros((2,3))
print(nl_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
nl2_array = np.ones((2,3))
print(nl2_array)

[[1. 1. 1.]
 [1. 1. 1.]]


# full array


In [8]:
full_array = np.full((10,10),7)
print(full_array)

[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]


# to create sequence of number arange(start,stop,step)

In [9]:
array1 = np.arange(1,10,3)
print(array1)

[1 4 7]


# identity matrices

In [10]:
identity_matrices = np.eye((3))
print(identity_matrices)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# know the shape of array using .shape function in short to know the dimensions

In [ ]:
array2 = np.array([[5,10,6],
                  [8,2,3]])
print(array2.shape)

# size is used for to know how many elements are there in array

In [ ]:
array3 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array3.size)

# .ndim function is used to see that how many number of dimensions are exist

In [ ]:
arr4 = np.array([10,20,30])
arr5 = np.array([[10,20,30],[40,50,60]])
arr6 = np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(arr4.ndim)
print(arr5.ndim)
print(arr6.ndim)

# .dtype function used to know that what are the data types are there present in array like int float string

In [11]:
arr7 = np.array([10,20,30])
arr8 = np.array([[10,20.5,30],[40,50,60]])

print(arr7.dtype)
print(arr8.dtype)

int64
float64


# .astype is used to convert one datatype into another one

In [12]:
arr9 = np.array([5.6,8,8.9])
print(arr9.dtype)
int_arr = arr9.astype(int)
print(int_arr)
print(int_arr.dtype)

float64
[5 8 8]
int64


# some mathimatical operations

In [ ]:
arr10 = np.array([10,20,30])
print(arr10 + 5)
print(arr10 - 5)
print(arr10 * 5)
print(arr10 / 5)
print(arr10 ** 5)
print(arr10 // 5)

# aggregation function is used to summerize all of the data means perfoming some operation on it
1. np.sum(array)
2. np.mean(array)
3. np.max(array)
4. np.min(array)
5. np.std(array)
7. np.var(array)

In [13]:
arr11 = np.array([10,20,30,40,50,60,70])
print(np.sum(arr11))
int_type = np.mean(arr11)
print(int_type.astype(int))
print(np.max(arr11))
print(np.min(arr11))
int_type2 = np.std(arr11)
print(int_type2.astype(int))
int_type3 = np.var(arr11)
print(int_type3.astype(int))

280
40
70
10
20
400


# indexing : to access particular element from an array by it's index

1. for 1d array : array[row]
2. for 2d array : array[row,column]



In [16]:
arr23 = np.array([50,60,70])
arr24 = np.array([[50,60,70],[50,90,80]])
print(arr23[1])
print(arr24[0,2])

60
70


# slicing : extracting subarray from a main array
  array[start:stop:step]

In [17]:
arr25 = np.array([10,50,60,70,80,20,30])
print(arr25[0:5])
print(arr25[:5])
print(arr25[0:])
print(arr25[::-1])
print(arr25[0:8])

[10 50 60 70 80]
[10 50 60 70 80]
[10 50 60 70 80 20 30]
[30 20 80 70 60 50 10]
[10 50 60 70 80 20 30]


# fancy indexing : selecting multiple elements at once

In [ ]:
arr26 = np.array([10,50,60,70,80,20,30])
print(arr26[[0,2,5]])

[10 60 20]


# boolean masking : selecting or filtering elements based upon conditions, in this there is copy of main array is created so after condition main array remain unchanged there is no changes occures on it

In [23]:
arr27 = np.array([10,50,60,70,80,20,30])
print(arr27[arr27 > 20])

[50 60 70 80 30]
