In [2]:
import numpy as np


In [2]:
n_array = np.array([1,2,3])

In [3]:
print(n_array)



[1 2 3]


In [4]:
nl_array = np.zeros((2,3))
print(nl_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
nl2_array = np.ones((2,3))
print(nl2_array)

[[1. 1. 1.]
 [1. 1. 1.]]


# full array


In [6]:
full_array = np.full((10,10),7)
print(full_array)

[[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]


# to create sequence of number arange(start,stop,step)

In [7]:
array1 = np.arange(1,10,3)
print(array1)

[1 4 7]


# identity matrices

In [5]:
identity_matrices = np.eye((3))
print(identity_matrices)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# know the shape of array using .shape function in short to know the dimensions

In [9]:
array2 = np.array([[5,10,6],
                  [8,2,3]])
print(array2.shape)

(2, 3)


# size is used for to know how many elements are there in array

In [10]:
array3 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array3.size)

9


# .ndim function is used to see that how many number of dimensions are exist

In [11]:
arr4 = np.array([10,20,30])
arr5 = np.array([[10,20,30],[40,50,60]])
arr6 = np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(arr4.ndim)
print(arr5.ndim)
print(arr6.ndim)

1
2
3


# .dtype function used to know that what are the data types are there present in array like int float string

In [12]:
arr7 = np.array([10,20,30])
arr8 = np.array([[10,20.5,30],[40,50,60]])

print(arr7.dtype)
print(arr8.dtype)

int64
float64


# .astype is used to convert one datatype into another one

In [13]:
arr9 = np.array([5.6,8,8.9])
print(arr9.dtype)
int_arr = arr9.astype(int)
print(int_arr)
print(int_arr.dtype)

float64
[5 8 8]
int64


# some mathimatical operations

In [14]:
arr10 = np.array([10,20,30])
print(arr10 + 5)
print(arr10 - 5)
print(arr10 * 5)
print(arr10 / 5)
print(arr10 ** 5)
print(arr10 // 5)

[15 25 35]
[ 5 15 25]
[ 50 100 150]
[2. 4. 6.]
[  100000  3200000 24300000]
[2 4 6]


# aggregation function is used to summerize all of the data, means perfoming some operation on it
1. np.sum(array)
2. np.mean(array)
3. np.max(array)
4. np.min(array)
5. np.std(array)
7. np.var(array)

In [15]:
arr11 = np.array([10,20,30,40,50,60,70])
print(np.sum(arr11))
int_type = np.mean(arr11)
print(int_type.astype(int))
print(np.max(arr11))
print(np.min(arr11))
int_type2 = np.std(arr11)
print(int_type2.astype(int))
int_type3 = np.var(arr11)
print(int_type3.astype(int))

280
40
70
10
20
400


# indexing : to access particular element from an array by it's index -> starts with zero

1. for 1d array : array[row]
2. for 2d array : array[row,column]



In [16]:
arr23 = np.array([50,60,70])
arr24 = np.array([[50,60,70],[50,90,80]])
print(arr23[1])
print(arr24[0,2])

60
70


# slicing : extracting subarray from a main array
  array[start:stop:step]

In [17]:
arr25 = np.array([10,50,60,70,80,20,30])
print(arr25[0:5])
print(arr25[:5])
print(arr25[0:])
print(arr25[::-1])
print(arr25[0:8])

[10 50 60 70 80]
[10 50 60 70 80]
[10 50 60 70 80 20 30]
[30 20 80 70 60 50 10]
[10 50 60 70 80 20 30]


# fancy indexing : selecting multiple elements at once

In [18]:
arr26 = np.array([10,50,60,70,80,20,30])
print(arr26[[0,2,5]])

[10 60 20]


# boolean masking : selecting or filtering elements based upon conditions, in this there is copy of main array is created so after condition main array remain unchanged there is no changes occures on it

In [19]:
arr27 = np.array([10,50,60,70,80,20,30])
print(arr27[arr27 > 20])

[50 60 70 80 30]


# reshaping : changing dimensions of given array without changing elements of it and it happen if dimentions match means if array is likely eligible to convert into other dimensions
-> reshaping returns view means it will create new array from an old array and old array get affected

In [20]:
arr33 = np.array([2,3,5,6,8,9,5,9])
print(arr33.reshape(2,4))

[[2 3 5 6]
 [8 9 5 9]]


# .ravel() -> gives view of array means changes in array
.flatten() -> gives copy of an array - >>> these both are used to convert multidimensional array to 1d array

In [21]:
arr33 = np.array([[3,5,6],[8,9,5]])
print(arr33.ravel())
print(arr33.flatten())

[3 5 6 8 9 5]
[3 5 6 8 9 5]


# .insert to insert value in array because it has fixed size and we have to add manually there
0. syntax : .insert(array, index, value, axis) axis = 0 -> row wise, axis = 1 -> column wise

In [22]:
arr33 = np.array([3,5,6,8,9,5])
print(np.insert(arr33,2,100,axis=0))

[  3   5 100   6   8   9   5]


In [23]:
arr33 = np.array([[3,5,9],[8,9,6],[5,9,8]])
print(np.insert(arr33,1,[5,6,8],axis=1))

[[3 5 5 9]
 [8 6 9 6]
 [5 8 9 8]]


# .append is used to add array after the array and it will give the copy of the array

In [24]:
arr33 = np.array([3,5,6,8,9,5])
print(arr33)
print(np.append(arr33,[5,9,8]))

[3 5 6 8 9 5]
[3 5 6 8 9 5 5 9 8]


# .concatenate used to add two arrays
axis = 0 -> vertical stacking
axis = 1 -> horizontal stacking

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2),axis=0))

[1 2 3 4 5 6]


# .delete is used to delete an array
# .delete(array, index, axis)
# it will return new array means copy

In [26]:
arr33 = np.array([3,5,6,8,9,5])
print(np.delete(arr33,0,axis=None))

[5 6 8 9 5]


In [27]:
arr33 = np.array([[3,5,6],[8,9,5]])
print(np.delete(arr33,0,axis=0))

[[8 9 5]]


# stacking : is used to stack the data
1. vertically -> vstack() -> row wise
2. horizotally -> hstack() -> column wise

In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# .split is used to split the array into equal parts and it's also gives an copy of original array
# .hsplit for horizontal splitting
# .vsplit for vertical splitting

In [29]:
arr33 = np.array([6,8,9,5])
print(arr33)
print(np.hsplit(arr33,2))

[6 8 9 5]
[array([6, 8]), array([9, 5])]


In [30]:
arr33 = np.array([[6,8],[9,5]])
print(arr33)
print(np.vsplit(arr33,2))

[[6 8]
 [9 5]]
[array([[6, 8]]), array([[9, 5]])]


# broadcasting : used to perform mathamatical operation faster and easily without need of loops and it will expand smaller array to larger array

In [31]:
arr33 = np.array([6,8,9,5])
print(arr33*2)

[12 16 18 10]


In [32]:
matrix = np.array([6,8]) # 1d array
vector = np.array([[6,8],[9,5]]) # 2d array
print(matrix + vector)

[[12 16]
 [15 13]]


In [33]:
matrix = np.array([6,8,5,6,8,9]) # 1d array
tap = matrix.reshape(2,3)
vector = np.array([[6,8,5],[9,5,7]]) # 2d array
print(tap + vector)

[[12 16 10]
 [15 13 16]]


# vectorization : performing operations on entire array without using a loop at once

In [34]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 * arr2)

[ 4 10 18]


# handling missing values:
1. np.isnan -> detect missing values
2. np.nan_to_num() -> convert nan to number
3. np.isinf() -> handle the infinite value
# we can not compare np.nan == np.nan directly


In [35]:
arr33 = np.array([6,8,9,np.nan,5])
print(np.isnan(arr33))

[False False False  True False]


In [36]:
arr33 = np.array([6,8,9,np.nan,5])
print(np.nan_to_num(arr33, nan = 5))

[6. 8. 9. 5. 5.]


In [37]:
arr33 = np.array([6,8,9,np.inf,5,-np.inf])
print(np.isinf(arr33))

[False False False  True False  True]


In [38]:
arr33 = np.array([6,8,9,np.inf,5,-np.inf])
print(np.nan_to_num(arr33, posinf = 10, neginf = -10))

[  6.   8.   9.  10.   5. -10.]
